const USER_ROLES_CONSTANTS = {
  ADMIN: 'ADMIN',
  BACKOFFICE_ADMIN: 'BACKOFFICE_ADMIN',
  GENERAL_MANAGER: 'GENERAL_MANAGER',
  REGIONAL_SALES_MANAGER: 'REGIONAL_SALES_MANAGER',
  AREA_SALES_MANAGER: 'AREA_SALES_MANAGER',
  SALES_OFFICER: 'SALES_OFFICER',
  TERRITORY_SALES_INCHARGE: 'TERRITORY_SALES_INCHARGE',
};

const CUSTOMER_CONSTANTS = {
  SUPER_STOCKIST: 'SUPER_STOCKIST',
  PRIMARY_DISTRIBUTOR: 'PRIMARY_DISTRIBUTOR',
  SECONDARY_DISTRIBUTOR: 'SECONDARY_DISTRIBUTOR',
  RETAILER: 'RETAILER',
};

const DISTRIBUTION_TYPES = {
  SUPERSTOCKIST_DISTRIBUTOR_RETAILER: 'SUPERSTOCKIST_DISTRIBUTOR_RETAILER',
  DISTRIBUTOR_RETAILER: 'DISTRIBUTOR_RETAILER',
  WHOLESALE_RETAILER: 'WHOLESALE_RETAILER',
  DIRECT_RETAILER: 'DIRECT_RETAILER',
};

const ORDER_TYPES = {
  PRIMARY_ORDER: 'PRIMARY_ORDER',
  SECONDARY_ORDER: 'SECONDARY_ORDER',
  SECOND_PRIMARY_ORDER: 'SECOND_PRIMARY_ORDER',
};

const ORDER_STATUS = {
  ORDERED: 'ORDERED',
  ORDER_APPROVED: 'ORDER_APPROVED',
  ORDER_CANCELLED_BY_FACTORY: 'ORDER_CANCELLED_BY_FACTORY',
  ORDER_CANCELLED_BY_SUPER_STOCKIST: 'ORDER_CANCELLED_BY_SUPER_STOCKIST',
  ORDER_CANCELLED_BY_DISTRIBUTOR: 'ORDER_CANCELLED_BY_DISTRIBUTOR',
  ORDER_CANCELLED_BY_RETAILER: 'ORDER_CANCELLED_BY_RETAILER',
  REACHED_DESTINATION: 'REACHED_DESTINATION',
};

const SKU_TYPES = {
  SKU: 'SKU',
  COMBO_SKU: 'COMBO_SKU',
};

const ACTIVITY_CONSTANTS = {
  ADD_OPENING_STOCK: 'Added Opening Stock',
  ADD_NEW_STOCK: 'Added to Inventory',
};

module.exports = {
  USER_ROLES_CONSTANTS,
  CUSTOMER_CONSTANTS,
  DISTRIBUTION_TYPES,
  ORDER_TYPES,
  ORDER_STATUS,
  SKU_TYPES,
  ACTIVITY_CONSTANTS,
};
