const USER_ROLES_CONSTANTS = {
  ADMIN: "ADMIN",
  BACKOFFICE_ADMIN: "BACKOFFICE_ADMIN",
  GENERAL_MANAGER: "GENERAL_MANAGER",
  REGIONAL_SALES_MANAGER: "REGIONAL_SALES_MANAGER",
  AREA_SALES_MANAGER: "AREA_SALES_MANAGER",
  SALES_OFFICER: "SALES_OFFICER",
  TERRITORY_SALES_INCHARGE: "TERRITORY_SALES_INCHARGE",
};

const CUSTOMER_CONSTANTS = {
  SUPER_STOCKIST: "SUPER_STOCKIST",
  DISTRIBUTOR: "DISTRIBUTOR",
  RETAILER: "RETAILER",
};

const DISTRIBUTION_TYPES = {
  SUPERSTOCKIST_DISTRIBUTOR_RETAILER: "SUPERSTOCKIST_DISTRIBUTOR_RETAILER",
  DISTRIBUTOR_RETAILER: "DISTRIBUTOR_RETAILER",
  WHOLESALE_RETAILER: "WHOLESALE_RETAILER",
  DIRECT_RETAILER: "DIRECT_RETAILER",
};

const ORDER_TYPES = {
  PRIMARY_ORDER: "PRIMARY_ORDER",
  SECONDARY_ORDER: "SECONDARY_ORDER",
  SECOND_PRIMARY_ORDER: "SECOND_PRIMARY_ORDER",
};

const ORDER_STATUS = {
  WAITING_FOR_APPROVAL: "WAITING_FOR_APPROVAL",
  APPROVED_BY_COMPANY: "APPROVED_BY_COMPANY",
  CANCELLED: "CANCELLED",
};

module.exports = {
  USER_ROLES_CONSTANTS,
  CUSTOMER_CONSTANTS,
  DISTRIBUTION_TYPES,
  ORDER_TYPES,
  ORDER_STATUS,
};
