const USER_ROLES_CONSTANTS = {
  REGIONAL_SALES_MANAGER: "REGIONAL_SALES_MANAGER",
  AREA_SALES_MANAGER: "AREA_SALES_MANAGER",
  SALES_OFFICER: "SALES_OFFICER",
  TERRITORY_SALES_INCHARGE: "TERRITORY_SALES_INCHARGE",
};

const DISTRIBUTION_TYPES = {
  SUPERSTOCKIST_DISTRIBUTOR_RETAILER: "SUPERSTOCKIST_DISTRIBUTOR_RETAILER",
  DISTRIBUTOR_RETAILER: "DISTRIBUTOR_RETAILER",
  WHOLESALE_RETAILER: "WHOLESALE_RETAILER",
  DIRECT_RETAILER: "DIRECT_RETAILER",
};

module.exports = {
  USER_ROLES_CONSTANTS,
  DISTRIBUTION_TYPES,
};
